apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: monolith
spec:
  interval: 10m0s
  component: phoban.io/monolith
  version:
    semver: "v1.0.1"
  repository:
    url: ghcr.io/mayankraipure12/phoban01
    secretRef:
      name: creds
  verify:
  - name: default
    publicKey:
      secretRef:
        name: alice-publickey1
  references:
    expand: true
