apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      initContainers: []
      containers: []
